# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Projects\WAP64

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Projects\WAP64

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\cmake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\cmake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\WAP64\CMakeFiles D:\Projects\WAP64\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\WAP64\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WAP64

# Build rule for target.
WAP64: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 WAP64
.PHONY : WAP64

# fast build rule for target.
WAP64/fast:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/build
.PHONY : WAP64/fast

#=============================================================================
# Target rules for targets named wap32

# Build rule for target.
wap32: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 wap32
.PHONY : wap32

# fast build rule for target.
wap32/fast:
	$(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/build
.PHONY : wap32/fast

src/PlayLevel.obj: src/PlayLevel.cpp.obj

.PHONY : src/PlayLevel.obj

# target to build an object file
src/PlayLevel.cpp.obj:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/PlayLevel.cpp.obj
.PHONY : src/PlayLevel.cpp.obj

src/PlayLevel.i: src/PlayLevel.cpp.i

.PHONY : src/PlayLevel.i

# target to preprocess a source file
src/PlayLevel.cpp.i:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/PlayLevel.cpp.i
.PHONY : src/PlayLevel.cpp.i

src/PlayLevel.s: src/PlayLevel.cpp.s

.PHONY : src/PlayLevel.s

# target to generate assembly for a file
src/PlayLevel.cpp.s:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/PlayLevel.cpp.s
.PHONY : src/PlayLevel.cpp.s

src/common.obj: src/common.cpp.obj

.PHONY : src/common.obj

# target to build an object file
src/common.cpp.obj:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/common.cpp.obj
.PHONY : src/common.cpp.obj

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/res.obj: src/res.cpp.obj

.PHONY : src/res.obj

# target to build an object file
src/res.cpp.obj:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/res.cpp.obj
.PHONY : src/res.cpp.obj

src/res.i: src/res.cpp.i

.PHONY : src/res.i

# target to preprocess a source file
src/res.cpp.i:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/res.cpp.i
.PHONY : src/res.cpp.i

src/res.s: src/res.cpp.s

.PHONY : src/res.s

# target to generate assembly for a file
src/res.cpp.s:
	$(MAKE) -f CMakeFiles\WAP64.dir\build.make CMakeFiles/WAP64.dir/src/res.cpp.s
.PHONY : src/res.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... WAP64
	@echo ... wap32
	@echo ... src/PlayLevel.obj
	@echo ... src/PlayLevel.i
	@echo ... src/PlayLevel.s
	@echo ... src/common.obj
	@echo ... src/common.i
	@echo ... src/common.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/res.obj
	@echo ... src/res.i
	@echo ... src/res.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

